--- Makefile    2019-11-22 12:00:00.000000000 -0500
+++ Makefile    2019-11-22 12:00:00.000000000 -0500
@@ -39,7 +39,7 @@
            vcfnorm.o vcfgtcheck.o vcfview.o vcfannotate.o vcfroh.o vcfconcat.o \
            vcfcall.o mcall.o vcmp.o gvcf.o reheader.o convert.o vcfconvert.o tsv2vcf.o \
            vcfcnv.o HMM.o consensus.o ploidy.o bin.o hclust.o version.o \
-           regidx.o smpl_ilist.o csq.o vcfbuf.o \
+           regidx.o smpl_ilist.o csq.o vcfbuf.o vcfmocha.o genome_rules.o beta_binom.o \
            mpileup.o bam2bcf.o bam2bcf_indel.o bam_sample.o \
            vcfsort.o cols.o \
            ccall.o em.o prob1.o kmin.o # the original samtools calling
@@ -268,6 +268,9 @@
 hclust.o: hclust.c $(htslib_hts_h) $(htslib_kstring_h) $(bcftools_h) hclust.h
 HMM.o: HMM.c $(htslib_hts_h) HMM.h
 vcfbuf.o: vcfbuf.c $(htslib_vcf_h) $(htslib_vcfutils_h) $(bcftools_h) $(vcfbuf_h) rbuf.h
+vcfmocha.o: vcfmocha.c $(htslib_vcf_h) $(htslib_synced_bcf_reader_h) $(htslib_kfunc_h) $(bcftools_h)
+genome_rules.o: genome_rules.c genome_rules.h
+beta_binom.o: beta_binom.c beta_binom.h
 smpl_ilist.o: smpl_ilist.c $(bcftools_h) $(smpl_ilist_h)
 csq.o: csq.c $(htslib_hts_h) $(htslib_vcf_h) $(htslib_synced_bcf_reader_h) $(htslib_khash_h) $(htslib_khash_str2int_h) $(htslib_kseq_h) $(htslib_faidx_h) $(bcftools_h) $(filter_h) regidx.h kheap.h $(smpl_ilist_h) rbuf.h
 
